default_stages: [commit]

repos:
  # Check formatting and lint for starlark code
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 8.2.1.1
    hooks:
      - id: buildifier
        args: ["-mode=fix", "-lint=fix"]
      - id: buildifier-lint
  # Enforce that commit messages allow for later changelog generation
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.8
    hooks:
      # Requires that commitizen is already installed
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.11.0
    hooks:
      - id: shellcheck
